name: Haskell Integration

on:
  push:
    branches:
      - master

    tags:
      - "v*"

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 17 * * *"

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.2.1"
          - "9.0.1"
          - "8.10.7"
          - "8.8.4"
        may-fail:
          - false
    continue-on-error: ${{ matrix.may-fail }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal configure --disable-documentation --enable-tests --disable-optimization

      - run: cabal build --dependencies-only all

      - run: cabal build all

      - run: cabal test all

  HLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-hlint

      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: "8.10.7"

      - name: Install HLint
        run: cabal install --installdir=. hlint --constraint 'hlint >= 3.3'

      - name: Run HLint
        run: ./hlint .

  UploadCandidate:
    runs-on: ubuntu-latest
    environment: hackage
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs:
      - BuildAndTest
      - HLint
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1.2

      - run: cabal sdist -o .

      - run: cabal upload -u ${{ secrets.HACKAGE_USER }} -p ${{ secrets.HACKAGE_PASSWORD }} ./simpoole-*.tar.gz
